---
task-definitions:
  - &terraform-setup
    task: prepare-terraform-env
    file: cpi-release-src/ci/tasks/prepare-terraform-env.yml
    params:
      oracle_tenancy: ((oracle-tenancy))
      oracle_user: ((oracle-user))
      oracle_region: ((oracle-region))
      oracle_fingerprint: ((oracle-fingerprint))
      oracle_apikey: ((oracle-apikey))
      director_vcn: ((director-vcn))
      director_compartment_name: ((director-compartment-name))
      director_subnet_cidr: ((director-subnet-cidr))

  - &terraform-apply
    put: oci-resources-setup
    params:
      terraform_source: cpi-release-src/ci/terraform
      env_name: oci-test-env
      var_files: [terraform-env/oci.vars]
      plugin_dir: /.terraform.d/plugins/linux_amd64

  - &oci-tests
    task: oci-tests
    file: cpi-src/ci/tasks/oci-tests.yml
    params:
      TEST_SPEC: "Test_[^StemcellOps]"

  - &terraform-destroy
    put: oci-resources-setup
    params:
      terraform_source: cpi-release-src/ci/terraform
      env_name: oci-test-env
      action: destroy
      var_files: [terraform-env/oci.vars]
      plugin_dir: /.terraform.d/plugins/linux_amd64
    get_params:
        action: destroy

groups:
  - name: bosh-oracle-cpi-release
    jobs:
      - run-unittests
      - run-ocitests
      - build-candidate
      - create-director
      - build-final

jobs:
  - name: run-unittests
    plan:
      - {trigger: true, get: cpi-src, resource: bosh-cpi-src}

      - task: unit-tests
        file: cpi-src/ci/tasks/unit-tests.yml

  - name: run-ocitests
    serial: true
    plan:
      - aggregate:
        - {trigger: true, passed: [run-unittests], get: cpi-src, resource: bosh-cpi-src}
        - {trigger: true, get: oci-config, resource: fixture-env, params: {file: oci-config.tgz, unpack: true}}

      - <<: *terraform-setup
      - <<: *terraform-apply
      - do:
        - <<: *oci-tests
        ensure:
          do:
            - <<: *terraform-destroy

  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - {trigger: true, passed: [run-unittests, run-ocitests], get: cpi-src, resource: bosh-cpi-src}
        - {trigger: true, get: cpi-release-src, resource: bosh-cpi-release-src}
        - {trigger: false, get: dev-version-semver,   params: {bump: patch}}

      - put: dev-version-semver
        params: {file: dev-version-semver/version}

      - task: build-dev-release
        file: cpi-release-src/ci/tasks/build-candidate.yml

      - put: dev-release-cpi
        params: {file: candidate/dev_release/bosh-oracle-cpi-dev-*.tgz}

  - name: create-director
    serial_groups: [run-bats]
    plan:
      - aggregate:
        - {trigger: true, passed: [build-candidate], get: cpi-src, resource: bosh-cpi-src}
        - {trigger: true, passed: [build-candidate], get: cpi-release-src, resource: bosh-cpi-release-src}
        - {trigger: true, passed: [build-candidate], get: candidate, resource: dev-release-cpi}
        - {trigger: true,                            get: oci-config, resource: fixture-env, params: {file: oci-config.tgz, unpack: true}}
        - {trigger: false,                           get: bosh-release}

      - task: setup-director
        file: cpi-release-src/ci/tasks/setup-director.yml

        on_failure:
          task: teardown-director
          file: cpi-release-src/ci/tasks/teardown-director.yml

  - name: build-final
    serial: true
    plan:
      - aggregate:
         - {trigger: false, get: final-version-semver,   params: {bump: major}}
         - {trigger: true, passed: [run-ocitests], get: cpi-src, resource: bosh-cpi-src}

      - task: build-final-release
        file: cpi-release-src/ci/tasks/build-final-release.yml

      - put: final-version-semver
        params: {file: final-version-semver/version}

      - put: final-release-cpi
        params:
          file: candidate/release/bosh-oracle-cpi-*.tgz

resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: dmutreja/oci-terraform-resource

resources:
  - name: bosh-cpi-release-src
    type: git
    source:
      uri: https://github.com/((github-org))/bosh-oracle-cpi-release.git
      branch: ((cpi-release-branch)) 
      username: ((github-user))
      password: ((github-password))

  - name: bosh-cpi-src
    type: git
    source:
      uri: https://github.com/((github-org))/bosh-oracle-cpi.git
      branch: ((cpi-branch))
      username: ((github-user))
      password: ((github-password))

  - name: dev-release-cpi
    type: s3
    source:
       endpoint: https://((oracle-namespace)).compat.objectstorage.((oracle-region)).oraclecloud.com
       region_name: ((oracle-region))
       bucket: ((cpi-dev-release-bucket))
       regexp: bosh-oracle-cpi-(.*).tgz
       access_key_id: ((oracle-s3-access-key-id))
       secret_access_key: ((oracle-s3-secret-access-key))
       private: true

  - name: final-release-cpi
    type: s3
    source:
       endpoint: https://((oracle-namespace)).compat.objectstorage.((oracle-region)).oraclecloud.com
       region_name: ((oracle-region))
       bucket: ((cpi-final-release-bucket))
       regexp: bosh-oracle-cpi-(.*).tgz
       access_key_id: ((oracle-s3-access-key-id))
       secret_access_key: ((oracle-s3-secret-access-key))
       private: true

  - name: dev-version-semver
    type: semver
    source:
      key: current-dev-version
      bucket: ((version-semver-bucket-name))
      access_key_id: ((oracle-s3-access-key-id))
      secret_access_key: ((oracle-s3-secret-access-key))
      region_name: ((oracle-region))
      endpoint: https://((oracle-namespace)).compat.objectstorage.((oracle-region)).oraclecloud.com
      initial_version:   0.0.36

  - name: final-version-semver
    type: semver
    source:
      key: current-final-version
      bucket: ((version-semver-bucket-name))
      access_key_id: ((oracle-s3-access-key-id))
      secret_access_key: ((oracle-s3-secret-access-key))
      region_name: ((oracle-region))
      endpoint: https://((oracle-namespace)).compat.objectstorage.((oracle-region)).oraclecloud.com
      initial_version: 1.0.0

  - name: fixture-env
    type: s3
    source:
       endpoint: https://((oracle-namespace)).compat.objectstorage.((oracle-region)).oraclecloud.com
       region_name: ((oracle-region))
       bucket: ((oracle-fixture-env-bucket-name))
       regexp: ((oracle-fixture-env))-(.*).tgz
       access_key_id: ((oracle-s3-access-key-id))
       secret_access_key: ((oracle-s3-secret-access-key))
       private: true

  - name: oci-resources-setup
    type: terraform
    source:
       storage:
         bucket: ((oracle-fixture-env-bucket-name))
         bucket_path: terraform-ci/
         access_key_id: ((oracle-s3-access-key-id))
         secret_access_key: ((oracle-s3-secret-access-key))
         region_name: ((oracle-region))
         endpoint: https://((oracle-namespace)).compat.objectstorage.((oracle-region)).oraclecloud.com
         use_signing_v4: true

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh
