---
groups:
  - name: bosh-oracle-cpi-release
    jobs:
      - test-unit
      - build-candidate
      - create-director
      - build-final

jobs:
  - name: test-unit
    plan:
      - {trigger: true, get: cpi-src, resource: bosh-cpi-src}

      - task: unit-tests
        file: cpi-src/ci/tasks/unit-tests.yml

  - name: build-candidate
    serial: true
    plan:
      - aggregate:
        - {trigger: true, passed: [test-unit], get: cpi-src, resource: bosh-cpi-src}
        - {trigger: true, get: cpi-release-src, resource: bosh-cpi-release-src}
        - {trigger: false, get: dev-version-semver,   params: {bump: patch}}

      - put: dev-version-semver
        params: {file: dev-version-semver/version}

      - task: build-dev-release
        file: cpi-release-src/ci/tasks/build-candidate.yml

      - put: dev-release-cpi
        params:
          file: candidate/dev_release/bosh-oracle-cpi-dev-*.tgz

    - name: create-director
      serial_groups: [run-bats]
      plan:
        - aggregate:
          - {trigger: true, passed: [build-candidate], get: cpi-src, resource: bosh-cpi-src}
          - {trigger: true, passed: [build-candidate], get: cpi-release-src, resource: bosh-cpi-release-src}
          - {trigger: true, passed: [build-candidate], get: candidate, resource: dev-release-cpi}
          - {trigger: true, passed: [build-candidate], get: stemcell, resource: oracle-ubuntu-stemcell}
          - {trigger: false,                           get: bosh-release}

        - task: setup-director
          file: cpi-release-src/ci/tasks/setup-director.yml
          params:
            oracle_tenancy:                 {{oracle_tenancy}}
            oracle_user:                    {{oracle_user}}
            oracle_compartment_id:          {{oracle_compartment_id}}
            oracle_compartment_name:        {{oracle_compartment_name}}
            oracle_region:                  {{oracle_region}}
            oracle_ad:                      {{oracle_ad}}
            oracle_fingerprint:             {{oracle_fingerprint}}
            oracle_apikey:                  {{oracle_apikey}}
            oracle_ssh_public_key:          {{oracle_ssh_public_key}}
            oracle_ssh_private_key:         {{oracle_ssh_private_key}}
          on_failure:
            task: teardown-director
            file: cpi-release-src/ci/tasks/teardown-director.yml

  - name: build-final
    serial: true
    plan:
      - aggregate:
         - {trigger: false, get: final-version-semver,   params: {bump: major}}
         - {trigger: true, passed: [build-candidate], get: cpi-release-src, resource: bosh-cpi-release-src}

      - task: build-final-release
        file: cpi-release-src/ci/tasks/build-final-release.yml

      - put: final-version-semver
        params: {file: final-version-semver/version}

      - put: final-release-cpi
        params:
          file: candidate/release/bosh-oracle-cpi-*.tgz

resources:
  - name: bosh-cpi-release-src
    type: git
    source:
      uri: https://github.com/((github-org))/bosh-oracle-cpi-release.git
      branch: ((cpi-release-branch)) 
      username: ((github-user))
      password: ((github-password))

  - name: bosh-cpi-src
    type: git
    source:
      uri: https://github.com/((github-org))/bosh-oracle-cpi.git
      branch: ((cpi-branch))
      username: ((github-user))
      password: ((github-password))

  - name: dev-release-cpi
    type: s3
    source:
       endpoint: https://((oracle-namespace)).compat.objectstorage.((oracle-region)).oraclecloud.com
       region_name: ((oracle-region))
       bucket: ((cpi-dev-release-bucket))
       regexp: bosh-oracle-cpi-(.*).tgz
       access_key_id: ((oracle-s3-access-key-id))
       secret_access_key: ((oracle-s3-secret-access-key))
       private: true

  - name: final-release-cpi
    type: s3
    source:
       endpoint: https://((oracle-namespace)).compat.objectstorage.((oracle-region)).oraclecloud.com
       region_name: ((oracle-region))
       bucket: ((cpi-final-release-bucket))
       regexp: bosh-oracle-cpi-(.*).tgz
       access_key_id: ((oracle-s3-access-key-id))
       secret_access_key: ((oracle-s3-secret-access-key))
       private: true

  - name: oracle-ubuntu-stemcell
    type: s3
    source:
       endpoint: https://((oracle-namespace)).compat.objectstorage.((oracle-region)).oraclecloud.com
       region_name: ((oracle-region))
       bucket: stemcells
       regexp: light-oracle-ubuntu-stemcell-2000.13.tgz
       access_key_id: ((oracle-s3-access-key-id))
       secret_access_key: ((oracle-s3-secret-access-key))
       private: true


  - name: dev-version-semver
    type: semver
    source:
      key: current-dev-version
      bucket: ((version-semver-bucket-name))
      access_key_id: ((oracle-s3-access-key-id))
      secret_access_key: ((oracle-s3-secret-access-key))
      region_name: ((oracle-region))
      endpoint: https://((oracle-namespace)).compat.objectstorage.((oracle-region)).oraclecloud.com
      initial_version:   0.0.36

  - name: final-version-semver
    type: semver
    source:
      key: current-final-version
      bucket: ((version-semver-bucket-name))
      access_key_id: ((oracle-s3-access-key-id))
      secret_access_key: ((oracle-s3-secret-access-key))
      region_name: ((oracle-region))
      endpoint: https://((oracle-namespace)).compat.objectstorage.((oracle-region)).oraclecloud.com
      initial_version: 1.0.0

   - name: bosh-release
     type: bosh-io-release
     source:
      repository: cloudfoundry/bosh