---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dmutreja/cpi-release-build-env
    tag: "latest"
inputs:
  - name: cpi-release-src
  - name: final-version-semver
outputs:
  - name: candidate
run:
  path: cpi-release-src/ci/tasks/build-final-release.sh
