---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dmutreja/oci-cli
    tag: "latest"
inputs:
  - name: cpi-release-src
  - name: dev-version-semver
outputs:
  - name: candidate
run:
  path: cpi-release-src/ci/tasks/download-cpi.sh
params:
  oracle_tenancy: replace-me
  oracle_user:    replace-me
  oracle_fingerprint: replace-me
  oracle_apikey:  replace-me
  oracle_region: replace-me
  oracle_namespace: replace-me
  oracle_bucket:  replace-me