---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dmutreja/cpi-release-build-env
    tag: "latest"
inputs:
  - name: cpi-src
  - name: cpi-release-src
  - name: bosh-release
  - name: candidate
  - name: stemcell
outputs:
  - name: deployment
run:
  path: cpi-src/ci/tasks/setup-director.sh
params:
  BOSH_LOG_LEVEL:                 debug
  BOSH_LOG_PATH:                  ./bosh-init.log
