---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: dmutreja/ubuntu-xenial-boshcliv2 
    tag: "latest"
inputs:
  - name: cpi-release-src
  - name: deployment
run:
  path: cpi-release-src/ci/tasks/teardown-director.sh
params:
  BOSH_LOG_LEVEL: debug
  BOSH_LOG_PATH:  ./bosh-init.log
